[package]
name = "dsa-ml"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-dilithium = "0.5.0"
axum = "0.8.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22.1"
subtle = "2.5.0"
dotenv = "0.15"
pqcrypto-traits = "0.3.5"