name: SBOM

on:
  push:
    branches: [ main ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cyclonedx-rust-cargo
        run: cargo install cyclonedx-bom
      - name: Generate SBOM
        run: cargo cyclonedx -o target/sbom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dilithium-sbom
          path: target/sbom.xml
