name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CycloneDX Rust
        run: cargo install cyclonedx-bom

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.xml

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
