name: SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install CycloneDX cargo subcommand
        run: cargo install --git https://github.com/CycloneDX/cyclonedx-rust-cargo.git --package cargo-cyclonedx --locked

      - name: Generate CycloneDX SBOM
        run: cargo cyclonedx -o sbom.xml

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
          retention-days: 7
