name: Signature test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Dilithium Signature Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Run tests
        run: cargo test --verbose
